### ISSUE TITLE
cert-manager error

### ISSUE THREAD

**Issue by mamtabhardwaj12** [aidtechnology/lf-k8s-hlf-webinar#1]
Hi Guys,

I am trying to do HLF on kubernetes. I am getting an error in a cert-manager pod which is up and running but when I saw logs of cert-manager pods, It shows something like in attached screenshots.
Kindly look into this issues.

'I1011 11:43:50.747198       1 start.go:79] starting cert-manager v0.5.0 (revision 7924346bd84e41053cc508956b0a1b567c932416)
I1011 11:43:50.747492       1 server.go:84] Listening on http://0.0.0.0:9402
I1011 11:43:50.748407       1 controller.go:126] Using the following nameservers for DNS01 checks: [10.96.0.10:53]
I1011 11:43:50.750399       1 leaderelection.go:175] attempting to acquire leader lease  cert-manager/cert-manager-controller...
I1011 11:45:20.198784       1 leaderelection.go:184] successfully acquired lease cert-manager/cert-manager-controller
I1011 11:45:20.199025       1 controller.go:68] Starting certificates controller
I1011 11:45:20.199061       1 controller.go:68] Starting issuers controller
I1011 11:45:20.199112       1 controller.go:68] Starting clusterissuers controller
I1011 11:45:20.199912       1 controller.go:68] Starting ingress-shim controller
I1011 11:49:47.075301       1 controller.go:140] clusterissuers controller: syncing item 'letsencrypt-staging'
I1011 11:49:47.075800       1 logger.go:88] Calling GetAccount
I1011 11:49:52.076363       1 helpers.go:147] Setting lastTransitionTime for ClusterIssuer "letsencrypt-staging" condition "Ready" to 2018-10-11 11:49:52.076342594 +0000 UTC m=+361.344961050
I1011 11:49:52.076599       1 sync.go:71] Error initializing issuer: Get https://acme-staging-v02.api.letsencrypt.org/directory: dial tcp: i/o timeout
E1011 11:49:52.213777       1 controller.go:149] clusterissuers controller: Re-queuing item "letsencrypt-staging" due to error processing: Get https://acme-staging-v02.api.letsencrypt.org/directory: dial tcp: i/o timeout
I1011 11:49:52.224125       1 controller.go:140] clusterissuers controller: syncing item 'letsencrypt-staging'
I1011 11:49:52.224650       1 logger.go:88] Calling GetAccount
I1011 11:49:57.225165       1 sync.go:71] Error initializing issuer: Get https://acme-staging-v02.api.letsencrypt.org/directory: dial tcp: i/o timeout`

Thanks & Regards,
Mamta

**Comment by alexvicegrab** [comment]
Hi Mamta,

Thanks for the post, this appears to be an issue with the certificate manager, which is maintained by the Helm charts repository. Hence it's outside the scope of this repository.

It looks like there is some issue with connecting to the ` https://acme-staging-v02.api.letsencrypt.org/directory`

Does your cluster have access to the internet?

Please re-post this issue here, where they have considerably more expertise with the `cert-manager`:

https://github.com/jetstack/cert-manager

Thanks for your interest in our Webinar.

Best!
Sasha
