### ISSUE TITLE
Which version of the Hyperledger Fabrics are supported?

### ISSUE THREAD

**Issue by yinwhm12** [aidtechnology/lf-k8s-hlf-webinar#4]
Sorry, I have some troubles to read the if-k8s-hlf-webinar. I am confused to which version of the charts(hlf-ord,hlf-peer...) you are using. I got that the image of fabric-network is 1.2.0(1.2.1) by the files of value.yaml. So i choose the following charts:
  hlf-ord is 1.2.2v;  hlf-peer is 1.2.0v
Action:
 1. use the fabric-tool creates the crypto material
 2. follow the values.yaml to fill some params
 3. launch the fabric-network(1.2 version) successful

Error:
  can not create channel
Error Info：create the channel command
 Error: got unexpoected status: BAD_REQUEST -- error authorizing update: error validationg DeltaSet: policy for [Group] /Channel/Application not satisfied: Failed to reach implicit threshold of 1 sub-policies, required 1 remaining command terminated with exit code 1

 orderer some errors:
   Evaluation Failed: Only 0 policies were satisfy policy /Channel/Application/ChannelCreationPolicy ...

I sure the crypto material is OK, because the orderer is running without error and the peer does so.
So i will be appreciated that you spend some time solving the troubles. TY(Thank you)

**Comment by yinwhm12** [comment]
and I find the parameter caServerTls in your values.yaml, but Official values.yaml did not contain the parameter. SO I' confused.

**Comment by yinwhm12** [comment]
my project is just simple, no ca ,no PV ... , just one orderer and one peer(one org)

**Comment by yinwhm12** [comment]
![image](https://user-images.githubusercontent.com/25929417/52107398-2d7e0f80-2631-11e9-9ce0-c1b7ac91eeeb.png)

![image](https://user-images.githubusercontent.com/25929417/52107416-3bcc2b80-2631-11e9-87ae-9a245a3873c4.png)

**Comment by alexvicegrab** [comment]
Hi @yinwhm12, I have been using 1.2 for the webinar, and have made things work also for version 1.3 as well.

The Webinar only shows how to deploy with a CA. Nowadays, I recommend that you check out the Workshop material instead (this has 2 examples, one with a single peer and orderer, without a CA, and one with multiple peers and orderers and a CA):

https://github.com/aidtechnology/hgf-k8s-workshop
