### ISSUE TITLE
Failed to connect to postgres database

### ISSUE THREAD

**Issue by paulrusu8** [aidtechnology/lf-k8s-hlf-webinar#7]
I have followed the tutorial to the point where one enrolls the ca-administrator with :
`
kubectl exec -n blockchain $CA_POD -- bash -c 'fabric-ca-client enroll -d -u http://$CA_ADMIN:$CA_PASSWORD@$SERVICE_DNS:7054'`.

However, I get the error: 

```
2019/04/17 20:35:35 [DEBUG] Received response
statusCode=500 (500 Internal Server Error)
Error: Response from server: Error Code: 0 - enroll handler failed to initialize DB: Failed to create user registry for PostgreSQL: Failed to connect to Postgres database. Postgres requires connecting to a specific database, the following databases were tried: [fabric_ca postgres template1]. Please create one of these database before continuing
```

This is all run in a minikube environement on an Ubuntu 18.04.2 machine. Does anyone know how to fix this?

**Comment by bizbi** [comment]
@paulrusu8 did you solve this?  I have the exact same problem!
